### ISSUE TITLE
Expert opinion on the value of the codebase

### ISSUE THREAD

**Issue by LifeIsStrange** [codeanticode/eliza#4]
@codeanticode 
Hi, yes this program (I mean the original ELIZA) is very famous historically.
However I wonder two things:
1) How much of a scam/fraud is it? 
I heard it is mainly composed of hardcoded input->output sequences. Is that true?
2) Is there one aspect of the program or a function that has legit usefulness and that you could recommend for someone starting a linguistic semantic parser from scracth ?

**Comment by codeanticode** [comment]
I don't think its a scam/fraud, not being an expert of the subject myself, I'd just say that is a very simple algorithm that applies some pattern matching on the input text to create a response that gives an impression of a conversation. Many more advanced chatbots have been created since Eliza, there a re plenty of resources online:

https://www.chatbotpack.com/how-eliza-chatbot-works/

https://en.wikipedia.org/wiki/ELIZA

**Comment by LifeIsStrange** [comment]
That makes sense. I am curious about the decomposition rule. Thanks for answering.
